Fix regression of errors when using Spark connect (#88)
In the latest v0.1.11 release, there is the following error when using
Spark connect:
```
ValidationError: 1 validation error for QuerySparkSQLTool
spark
  instance of SparkSession expected (type=type_error.arbitrary_type; expected_arbitrary_type=SparkSession)
```
This PR is to fix it.
We should have GA test later.